# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Silence the 'Limited Groovy DSL support for Stonecutter' message.
dev.kikugie.stonecutter.hard_mode=true
# Mod Properties (shared by all Minecraft versions)
mod_version=2.1.5
maven_group=me.mrbubbles.fastcrystal
archives_base_name=fastcrystal
